trigger:
  branches:
    include:
      - main
      - master
      - develop
      - staging

pr:
  branches:
    include:
      - main
      - master
      - develop
      - staging

parameters:
  - name: browser
    displayName: 'Seleccionar browser a ejecutar'
    type: string
    default: ' '
    values:
      - ' '
      - chrome
      - firefox
      - safari
      - edge
      - multipleNavegador
      - api
      - perf
      - ratelimit

  - name: folder
    displayName: 'Seleccionar folder a ejecutar'
    type: string
    default: ' '
    values:
      - ' '
      - portal
      - API

  - name: feature
    displayName: 'Seleccionar feature a ejecutar'
    type: string
    default: ' '
    values:
      - ' '
      - consultaRNC
      - ejecucionApi

  - name: tags
    displayName: 'Seleccionar tags a ejecutar'
    type: string
    default: ' '
    values:
      - ' '
      - '@smoke'
      - '@regression'
      - '@first'
      - '@smokeApi'

  - name: env
    displayName: 'Seleccionar ambiente de prueba'
    type: string
    default: ' '
    values:
      - ' '
      - dev
      - qa
      - prod

  - name: workers
    displayName: 'Insertar cantidad de ejecucion en workers'
    type: string
    default: ' '

  - name: data_file
    displayName: 'Seleccionar archivo de datos a ejecutar para pruebas de Performance'
    type: string
    default: ' '
    values:
      - ' '
      - apiExample

  - name: scenario
    displayName: 'Insertar el nombre del escenario a ejecutar para pruebas de Performance'
    type: string
    default: ' '

stages:
- stage: test
  jobs:
  - job: test
    timeoutInMinutes: 60

    strategy:
      matrix:
    #    macOs:
    #      poolName: 'onpremise'
    #      vmImage: 'macOs-latest'
        windows:
    #      poolName: 'onpremise'
          vmImage: 'windows-latest'
    #  maxParallel: 2  # Descomentar para agregar ejecucion en paralelo de multiples plataformas si existen varios agentes(hosted)

    variables:
    - ${{ if eq(parameters.env, ' ') }}:
      - group: vg_qa_framework_dev
    - ${{ else }}:
      - group: ${{ format('vg_qa_framework_{0}', parameters.env) }}
    - group: vg-qa-framework-pipelines-conf
    - ${{ if ne(parameters.browser, ' ') }}:
      - name: BROWSER
        value: ${{ parameters.browser }}
    - ${{ if ne(parameters.env, ' ') }}:
      - name: ENVIRONMENT
        value: ${{ parameters.env }}
    - ${{ if ne(parameters.tags, ' ') }}:
      - name: TAGS
        value: ${{ parameters.tags }}
    - ${{ if ne(parameters.folder, ' ') }}:
      - name: FOLDER
        value: ${{ parameters.folder }}
    - ${{ if ne(parameters.feature, ' ') }}:
      - name: FEATURE
        value: ${{ parameters.feature }}
    - ${{ if ne(parameters.data_file, ' ') }}:
      - name: DATA_FILE
        value: ${{ parameters.data_file }}
    - ${{ if ne(parameters.workers, ' ') }}:
      - name: WORKERS
        value: ${{ parameters.workers }}
    - ${{ if ne(parameters.scenario, ' ') }}:
      - name: SCENARIO
        value: ${{ parameters.scenario }}
    - name: HEADLESS
      value: true

    pool:
  #    name: $(poolName)
      vmImage: $(vmImage)

    steps:
      - checkout: self
        displayName: 'Clonar repositorio'

      - task: NodeTool@0
        inputs:
          versionSpec: '24.x'
        displayName: 'Configurar Node.js'

      - script: |
          npm ci
        displayName: 'Instalar dependencias de CI'

      - script: |
          npm run $(BROWSER) folder=$(FOLDER) data_file=$(DATA_FILE) feature=$(FEATURE) tags=$(TAGS) env=$(ENVIRONMENT) workers=$(WORKERS) scenario=$(SCENARIO)
        displayName: 'Ejecutar escenarios de prueba'
        env:
          AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/reports/playwright-report/'
          artifactName: 'ReporteHTML-$(vmImage)'
        condition: and(always(), ne(variables['BROWSER'], 'perf'))
        displayName: 'Generar artefacto de Reporte HTML para $(vmImage)'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/reports/K6-report/'
          artifactName: 'ReporteK6-$(vmImage)'
        condition: and(always(), eq(variables['BROWSER'], 'perf'))
        displayName: 'Generar artefacto de Reporte K6 para $(vmImage)'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)/logs/'
          artifactName: 'Logs-$(vmImage)'
        condition: always()
        displayName: 'Generar artefacto de logs para $(vmImage)'

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '$(Build.SourcesDirectory)/reports/temp/xml/*.xml'
          mergeTestResults: true
          testRunTitle: 'Cucumber JUnit Results'
          publishRunAttachments: true
        condition: and(always(), ne(variables['BROWSER'], 'perf'))
        displayName: 'Publicar Test Results'
