name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ,staging ]
  pull_request:
    branches: [ main, master, develop ,staging ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Seleccionar browser a ejecutar'
        required: false
        default: ''
        options:
          - 'chrome'
          - 'firefox'
          - 'safari'
          - 'edge'
          - 'multipleNavegador'
          - 'api'
          - 'perf'
      folder:
        type: choice
        description: 'Seleccionar folder a ejecutar'
        required: false
        default: ''
        options:
          - ''
          - 'portal'
      feature:
        type: choice
        description: 'Seleccionar feature a ejecutar'
        required: false
        default: ''
        options:
          - ''
          - 'consultaRNC'
          - 'AccederDGII'
          - 'ejecucionOracle'
          - 'ejecucionApi'
      tags:
        type: choice
        description: 'Seleccionar tags a ejecutar'
        required: false
        default: ''
        options:
          - ''
          - '@smoke'
          - '@regression'
          - '@first'
          - '@smokeApi'
      env:
        type: choice
        description: 'Seleccionar ambiente de prueba'
        required: true
        default: 'dev'
        options:
          - ''
          - 'dev'
          - 'qa'
          - 'prod'
      workers:
        type: string
        description: 'Insertar cantidad de ejecucion en workers'
        required: false
        default: ''
      data_file:
        type: choice
        description: 'Seleccionar archivo de datos a ejecutar para pruebas de Performance'
        required: false
        default: ''
        options:
          - ''
          - 'apiExample'
      scenario:
        type: string
        description: 'Insertar el nombre del escenario a ejecutar para pruebas de Performance'
        required: false
        default: ''
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  Test:
    timeout-minutes: 60
    runs-on: windows-latest
    env:
      BROWSER: ${{ github.event.inputs.browser || 'api' }}
      FOLDER: ${{ github.event.inputs.folder || '' }}
      FEATURE: ${{ github.event.inputs.feature || '' }}
      TAGS: ${{ github.event.inputs.tags || '@smokeApi' }}
      ENVIRONMENT: ${{ github.event.inputs.env || 'dev' }}
      WORKERS: ${{ github.event.inputs.workers || '' }}
      DATA_FILE: ${{ github.event.inputs.data_file || '' }}
      SCENARIO: ${{ github.event.inputs.scenario || '' }}
      HEADLESS: true
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v5
    - name: Configurar Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: npm run ${{ env.BROWSER }} folder=${{ env.FOLDER }} data_file=${{ env.DATA_FILE }} feature=${{ env.FEATURE }} tags=${{ env.TAGS }} env=${{ env.ENVIRONMENT }} workers=${{ env.WORKERS }} scenario=${{ env.SCENARIO }}      
    - name: Mostrar resultado
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: test-results
        path: |
          reports/playwright-report/*/*.html
          reports/K6-report/*.html
          logs/*.txt
        retention-days: 30
    - name: Report test results
      uses: dorny/test-reporter@v3
      if: ${{ env.BROWSER != 'perf' }}
      with:
        name: JUnit Report
        path: reports/temp/xml/*.xml
        reporter: java-junit